version: '3.7'

services:
  vernemq:
    image: erlio/docker-vernemq
    container_name: vernemq
    restart: always
    environment:
     - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
    ports:
      - "1883:1883"
      - "8889:8888"
    networks: 
      - duck

networks: 
  duck:
    driver: bridge